Pm 3789 optimize collection query
collective/collective.eeafaceted.collectionwidget pull request #8
Opened 2021-11-25 12:32 UTC by gbastien

2021-11-26 13:23 UTC, sgeulette requested changes
j'ai juste relu mais pas testé dans ia.docs...

2021-11-26 13:23 UTC, sgeulette commented on src/collective/eeafaceted/collectionwidget/tests/test_widget.py
> +        cleanRamCacheFor('collective.eeafaceted.collectionwidget.vocabulary.__call__')
sans avoir vérifié précisément mais comme il y a plusieurs vocabulaires "cachés" sur __call__, cela les concerne tous ?

2021-11-26 13:23 UTC, sgeulette commented on src/collective/eeafaceted/collectionwidget/widgets/widget.py
> +            from collective.eeafaceted.collectionwidget.utils import getCurrentCollection
c'est voulu cet import dans le code ?

2021-11-26 13:23 UTC, sgeulette commented on src/collective/eeafaceted/collectionwidget/browser/views.py
> +        # Begin changes, comment "path" aribitrary added
arbitrary

2021-11-26 13:23 UTC, sgeulette commented on src/collective/eeafaceted/collectionwidget/browser/views.py
> +        # End changes, comment "path" aribitrary added
arbitrary

2021-11-29 08:59 UTC, gbastien commented on src/collective/eeafaceted/collectionwidget/tests/test_widget.py
> +        cleanRamCacheFor('collective.eeafaceted.collectionwidget.vocabulary.__call__')
Salut @sgeulette 

il n'y a que CollectionCategoryVocabulary.__call__ qui est caché dans vocabulary, l'autre avec le décorateur @ram.cache est CachedCollectionVocabulary.  Justement sur CollectionCategoryVocabulary le cache est très agressif et genre jamais invalidé car on n'a presque jamais de changement de ce côté sauf en cas de migration et ajout d'un sous-dossier...  Sinon il faudrait tester dans la cachekey si un des sous-éléments a changé, mais du coup on perd l'intérêt comme çà n'arrive (presque) jamais...  Ici c'est juste dans le test qu'on invalide, sinon dans l'interface ce sera simplement jamais invalidé (sauf redémarrage instance, ce qui est le cas lors application nouvelle màj par exemple...)

2021-11-29 08:59 UTC, gbastien commented on src/collective/eeafaceted/collectionwidget/widgets/widget.py
> +            from collective.eeafaceted.collectionwidget.utils import getCurrentCollection
Oui pour éviter un circular import car le widget est aussi importé dans utils...

2021-12-02 07:45 UTC, sgeulette commented on src/collective/eeafaceted/collectionwidget/content/dashboardcollection.py
> +        """Overrided to not add the "path" in the qurey arbitrary,
query

2021-12-02 08:09 UTC, merged